apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elk
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          - /var/log/*.log  
          - /path/to/your/logs/app/*.log  
          - /path/to/other/logs/*.log  

    output.logstash:
      hosts: ["logstash:5044"]
