name: "02-ELKStack"
on:
  push:
    branches:
      - develop
      - main
jobs:
  deploy-elkstack:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: latest
          cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: us-east-1

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      - name: Install kubectl
        run: |
          sudo apt-get install -y kubectl

      - name: Configure kubectl for AWS EKS
        run: |
          aws eks update-kubeconfig --name module-eks-CPxup

      - name: Wait for Resources
        run: sleep 30

      - name: Deploy ELK Stack
        run: |
          cd modules/elk
          kubectl config view
          kubectl apply -f . --validate=false

      - name: Verify kubectl configuration
        run: |
          sleep 30
          kubectl get svc -n elk

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Tests
        run: mvn test

      - name: Build with Maven
        run: mvn clean install

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mateusbrazza/public-case-jwt:latest

      - name: Deploy Application
        run: |
          kubectl create deployment public-case-jwt --image=mateusbrazza/public-case-jwt:latest -n elk
          kubectl expose deployment public-case-jwt --type=LoadBalancer --port=8080 -n elk